name: action
on:
  push:
    branches: [main]
  schedule:
    - cron:  '0 0 * * *'
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: hadolint for controller
        run: docker run -e "HADOLINT_IGNORE=DL3008" --rm -i hadolint/hadolint < controller/Dockerfile
      - name: hadolint for compute
        run: docker run -e "HADOLINT_IGNORE=DL3008" --rm -i hadolint/hadolint < compute/Dockerfile
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Remove unused files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - uses: actions/checkout@v2
      - name: Install docker-compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.17.3
          legacy: true
      - name: Test Images
        run: |
          docker-compose up -d
          sleep 180
          docker-compose exec -T --user stack controller /bin/test.bash
